services:
  - name: nestjs-api
    rutime: Docker
    type: web
    env: node
    build:
      dockerfilePath: ./api/Dockerfile  
    plan: free  
    envVars:
      - key: DB_HOST
        value: nestjs-mysql-db
      - key: DB_PORT
        value: "3306"
      - key: DB_USERNAME
        value: user
      - key: DB_PASSWORD
        value: abc123
      - key: DB_DATABASE
        value: nestjs-mysql-db
    autoDeploy: true

  - name: nestjs-mysql-db
    type: web
    env: mysql
    plan: free  
    database: mysql
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: abc123
      - key: MYSQL_DATABASE
        value: users
      - key: MYSQL_USER
        value: user
      - key: MYSQL_PASSWORD
        value: abc123

