version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: nestjs_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}   
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  # mongodb:
  #   image: mongo:5.0
  #   container_name: nestjs_mongo_db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   ports:
  #     - '${MONGO_PORT}:27017'
  #   volumes:
  #     - mongo_data:/data/db
  #     - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    
  api:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: nestjs-container
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db 

volumes:
  mysql_data:
  mongo_data:

networks:
  backend_network:
    driver: bridge 